
version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "4000:4000"
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
  redis:
    image: redis:alpine